lidar:
  channel : 64
  VFoV_max : 22.5
  VFoV_min : -22.5
  Horizontal_res : 1024
  rotational_rate : 20 # rotation Hz 
  range_min : 1.5
  range_max : 120
  rotation_direction : 1 #[-1, 1] for ccw, cw 
  initial_scan : 180 # degree for initial scan, generaly 0 or 180
  velocity : 10  # m/s
  vector : [1, 0] #x, y, should be normalized 
